name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '40 4 * * *' # Run 4:40 every day

env:
  REGISTRY: ghcr.io
  EMBY_TAG: beta # <-- specify Emby version here
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mb3admin
        uses: docker/build-push-action@v5
        with:
          context: ./mb3admin
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/emby-mb3admin:latest
          
      - name: Build and push embyserver
        uses: docker/build-push-action@v5
        with:
          context: ./embyserver
          push: true
          build-args: |
            EMBY_TAG=${{ env.EMBY_TAG }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/emby-server:${{ env.EMBY_TAG }}
