name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '30 4 8 * *'

env:
  REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mb3admin
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:mb3admin"
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/emby-mb3admin:latest
          
      - name: Build and push embyserver
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/emby-server:latest
